language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
- rbx
env:
  matrix:
    secure: broNy0H5kw79xObhkjgk8D5plLECRpj3d+JMGM0HSZDmrQ43p7FN9Ofmg1vl0khOop6GH8XRdNuI2M6P6Gw9gniPSLtIVTDwWLlrVwpP1Uxp7X85uztduC+zBrpoUuRsxqDFwejblML9GUFJtZOC1yNLZsCGSSZPINtLIalaL/I=
